import React, { useState, useRef } from 'react';
import { openRouterAI } from '../services/openrouter';
import toast from 'react-hot-toast';

const CONTENT_TYPES = [
  { id: 'blog', label: 'Blog Post', icon: '📝', desc: 'SEO-optimized articles' },
  { id: 'social', label: 'Social Media', icon: '📱', desc: 'Posts for all platforms' },
  { id: 'email', label: 'Email Copy', icon: '📧', desc: 'Newsletters & campaigns' },
  { id: 'ad', label: 'Ad Copy', icon: '🎯', desc: 'Google & Meta ads' },
  { id: 'landing', label: 'Landing Page', icon: '🌐', desc: 'Conversion-focused' },
  { id: 'video', label: 'Video Script', icon: '🎬', desc: 'TikTok/Reels/YouTube' },
  { id: 'press', label: 'Press Release', icon: '📰', desc: 'Media announcements' },
  { id: 'product', label: 'Product Description', icon: '🏷️', desc: 'E-commerce copy' },
];

const TONES = ['Professional', 'Casual', 'Persuasive', 'Educational', 'Friendly', 'Urgent', 'Luxury', 'Humorous'];

export default function ContentWriter() {
  const [contentType, setContentType] = useState('blog');
  const [topic, setTopic] = useState('');
  const [keywords, setKeywords] = useState('');
  const [tone, setTone] = useState('Professional');
  const [length, setLength] = useState('medium');
  const [targetAudience, setTargetAudience] = useState('');
  const [generated, setGenerated] = useState('');
  const [title, setTitle] = useState('');
  const [generating, setGenerating] = useState(false);
  const [history, setHistory] = useState([]);
  const [wordCount, setWordCount] = useState(0);
  const contentRef = useRef(null);

  const generate = async () => {
    if (!topic) { toast.error('Enter a topic'); return; }
    setGenerating(true);
    try {
      const result = await openRouterAI.callAI([{ 
        role: 'user', 
        content: `Write a ${tone.toLowerCase()} ${contentType} about "${topic}". Keywords: ${keywords || 'none'}. Target audience: ${targetAudience || 'general'}. Length: ${length}. Return JSON: {"title":"Engaging Title Here","content":"Full content here with proper formatting and line breaks"}` 
      }]);
      const content = result?.content || result?.text || '';
      const generatedTitle = result?.title || `${topic} - ${contentType.charAt(0).toUpperCase() + contentType.slice(1)}`;
      setTitle(generatedTitle);
      setGenerated(typeof content === 'string' ? content : JSON.stringify(content));
      setWordCount((typeof content === 'string' ? content : '').split(/\s+/).length);
      setHistory(prev => [{ topic, type: contentType, title: generatedTitle, date: new Date().toISOString() }, ...prev].slice(0, 20));
      toast.success('Content generated!');
    } catch {
      const fallback = `# ${topic}\n\nThis is a sample ${contentType} about ${topic}. Generated content will appear here.`;
      setTitle(topic);
      setGenerated(fallback);
      setWordCount(fallback.split(/\s+/).length);
    } finally { setGenerating(false); }
  };

  const copyContent = () => { navigator.clipboard.writeText(`${title}\n\n${generated}`); toast.success('Copied!'); };

  const downloadTXT = () => {
    const text = `${title}\n${'='.repeat(title.length)}\n\n${generated}\n\n---\nGenerated by Nuage Digital Content Writer\nnuage-digital.com`;
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = `${title?.replace(/\s+/g, '-').toLowerCase()}.txt`; a.click();
    toast.success('Downloaded!');
  };

  const downloadPDF = () => {
    const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Georgia',serif;color:#1a1a1a;line-height:1.8;max-width:800px;margin:0 auto;padding:40px}
.header{text-align:center;border-bottom:3px solid #7c3aed;padding-bottom:30px;margin-bottom:40px}
.header h1{font-size:32px;color:#4c1d95;margin-bottom:10px}
.header .meta{font-size:14px;color:#6b7280}
.content{font-size:16px;white-space:pre-wrap}
.content h2{font-size:22px;color:#4c1d95;margin:25px 0 15px}
.content p{margin-bottom:15px}
.content ul{margin:15px 0;padding-left:25px}
.content li{margin-bottom:8px}
.footer{margin-top:50px;padding-top:20px;border-top:1px solid #e5e7eb;text-align:center;font-size:12px;color:#9ca3af}
@media print{body{-webkit-print-color-adjust:exact}}
</style></head><body>
<div class="header"><h1>${title}</h1><div class="meta">${CONTENT_TYPES.find(c=>c.id===contentType)?.label} • ${tone} Tone • ${wordCount} words • ${new Date().toLocaleDateString()}</div></div>
<div class="content">${generated.replace(/\n/g, '<br>')}</div>
<div class="footer"><p>Generated by Nuage Digital AI Content Writer</p><p>nuage-digital.com</p></div>
</body></html>`;

    const printWindow = window.open('', '_blank', 'width=900,height=700');
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => { printWindow.print(); toast.success('🖨️ Print → Save as PDF'); }, 1000);
  };

  const clearAll = () => { setGenerated(''); setTitle(''); setTopic(''); setKeywords(''); setWordCount(0); };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div><h1 className="text-2xl font-bold">✍️ AI Content Writer</h1><p className="text-sm text-gray-500">Generate marketing content & export as PDF</p></div>
        <div className="flex gap-2">
          {generated && <button onClick={clearAll} className="px-3 py-2 bg-gray-200 text-gray-700 rounded-lg text-xs font-medium">Clear</button>}
          <button onClick={generate} disabled={generating || !topic} className="px-4 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-lg text-sm font-medium disabled:opacity-50 whitespace-nowrap">
            {generating ? '⏳ Writing...' : '✨ Generate Content'}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Settings Panel */}
        <div className="space-y-4">
          {/* Content Type */}
          <div className="bg-white rounded-xl shadow-sm border p-4">
            <h3 className="font-semibold text-sm mb-3">📋 Content Type</h3>
            <div className="grid grid-cols-2 gap-2">
              {CONTENT_TYPES.map(ct => (
                <button key={ct.id} onClick={() => setContentType(ct.id)}
                  className={`p-3 rounded-lg text-center transition-all ${contentType === ct.id ? 'bg-purple-100 text-purple-700 border-2 border-purple-300 shadow-sm' : 'bg-gray-50 hover:bg-gray-100 border-2 border-transparent'}`}>
                  <div className="text-xl">{ct.icon}</div>
                  <div className="text-xs font-medium mt-1">{ct.label}</div>
                  <div className="text-[10px] text-gray-400">{ct.desc}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Settings */}
          <div className="bg-white rounded-xl shadow-sm border p-4">
            <h3 className="font-semibold text-sm mb-3">⚙️ Settings</h3>
            <div className="space-y-3">
              <div>
                <label className="text-xs font-medium text-gray-700">Topic *</label>
                <input type="text" value={topic} onChange={e => setTopic(e.target.value)} 
                  placeholder="e.g., Benefits of SEO for dentists" 
                  className="w-full px-3 py-2 border rounded-lg text-sm mt-1 focus:ring-2 focus:ring-purple-500 focus:border-transparent" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Keywords</label>
                <input type="text" value={keywords} onChange={e => setKeywords(e.target.value)} 
                  placeholder="seo, dentist, marketing" 
                  className="w-full px-3 py-2 border rounded-lg text-sm mt-1" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Target Audience</label>
                <input type="text" value={targetAudience} onChange={e => setTargetAudience(e.target.value)} 
                  placeholder="e.g., small business owners" 
                  className="w-full px-3 py-2 border rounded-lg text-sm mt-1" />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700">Tone</label>
                  <select value={tone} onChange={e => setTone(e.target.value)} className="w-full px-3 py-2 border rounded-lg text-sm mt-1">
                    {TONES.map(t => <option key={t}>{t}</option>)}
                  </select>
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700">Length</label>
                  <select value={length} onChange={e => setLength(e.target.value)} className="w-full px-3 py-2 border rounded-lg text-sm mt-1">
                    <option value="short">Short (~200w)</option>
                    <option value="medium">Medium (~500w)</option>
                    <option value="long">Long (~1000w)</option>
                  </select>
                </div>
              </div>
            </div>
          </div>

          {/* History */}
          {history.length > 0 && (
            <div className="bg-white rounded-xl shadow-sm border p-4">
              <h3 className="font-semibold text-sm mb-3">📚 Recent ({history.length})</h3>
              <div className="space-y-1 max-h-64 overflow-y-auto">
                {history.map((h, i) => (
                  <div key={i} className="p-2.5 bg-gray-50 rounded-lg text-xs cursor-pointer hover:bg-gray-100 transition-colors" 
                    onClick={() => { setTopic(h.topic); setContentType(h.type); }}>
                    <div className="font-medium text-gray-800 truncate">{h.title}</div>
                    <div className="text-gray-500 flex items-center gap-2 mt-0.5">
                      <span>{CONTENT_TYPES.find(c=>c.id===h.type)?.icon}</span>
                      <span>{new Date(h.date).toLocaleDateString()}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Content Preview */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-xl shadow-sm border min-h-[500px] flex flex-col">
            <div className="px-6 py-4 border-b flex items-center justify-between flex-wrap gap-2">
              <div>
                <h3 className="font-semibold text-gray-900">
                  {generated ? '📄 Generated Content' : '📝 Content Preview'}
                </h3>
                {wordCount > 0 && <p className="text-xs text-gray-500">{wordCount} words • {tone} tone</p>}
              </div>
              {generated && (
                <div className="flex gap-1.5">
                  <button onClick={copyContent} className="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 rounded-lg text-xs font-medium transition-colors">📋 Copy</button>
                  <button onClick={downloadTXT} className="px-3 py-1.5 bg-blue-50 hover:bg-blue-100 text-blue-700 rounded-lg text-xs font-medium transition-colors">📥 TXT</button>
                  <button onClick={downloadPDF} className="px-3 py-1.5 bg-red-50 hover:bg-red-100 text-red-700 rounded-lg text-xs font-medium transition-colors">📄 PDF</button>
                </div>
              )}
            </div>
            <div className="flex-1 p-6 overflow-y-auto" ref={contentRef}>
              {generated ? (
                <div>
                  <h2 className="text-xl font-bold text-gray-900 mb-4">{title}</h2>
                  <div className="prose max-w-none text-sm whitespace-pre-wrap text-gray-700 leading-relaxed">{generated}</div>
                </div>
              ) : (
                <div className="h-full flex items-center justify-center text-gray-400">
                  <div className="text-center">
                    <p className="text-5xl mb-4">✍️</p>
                    <p className="font-medium text-gray-500">Enter a topic and generate content</p>
                    <p className="text-sm mt-2">Content will appear here with export options</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}